### ISSUE TITLE
Consider automatic deref

### ISSUE THREAD

**Issue by christianromney** [eggsyntax/datawalk#3]
Sometimes a complex data structure has something deref-able inside of it. This data is opaque to datawalk. It would be useful to automatically deref any node for which the predicate `(partial satisfies? IDeref)` is true when navigating to it with `(w)`. 

Also happy to contribute a PR if you feel this is something you'd accept.

**Comment by eggsyntax** [comment]
Terrific idea. I'll give that one a bit of thought to see if I see downsides, but unless something comes up, totally happy to make this change. It'll maybe take some consideration on how this ought to interact with backward, forward, and up.

Thanks!

**Comment by eggsyntax** [comment]
A few notes on this -- I'm experimenting with these options to try to see what feels like the cleanest solution.

*  Ideal solution:
   1) Works correctly with forward & backward
   2) Works properly with up.
   3) Works correctly with path
      - What does that even mean? A deref step means `get-in` will break anyway.
   4) Seems natural to users
*  Options:
   - Deref is an ordinary `drill` step
     1, 2, 4 - breaks 3 (by default)
   - Deref is a special command
     1, 2, 3?, 4?
   - Deref is implicit, you never see `atom`
     Not sure yet exactly what this or the next option would mean
   - Deref is a printing affordance only, can't drill
*  note that some derefables will cause problems, since they don't currently contain vals.
   - But `deref` optionally takes a timeout & a timeout-val; that should solve.
*  Togglable setting for deref behavior?

I may start with a minimal solution so that users have at least *some* way of handling derefables.

**Comment by eggsyntax** [comment]
It also occurs to me that `drill` may ultimately be better as a protocol so that users can define for any type what it means to drill into it.

**Comment by eggsyntax** [comment]
Fixed in 0.1.11, now on clojars. Deref is an ordinary drill step. LMK how that works out for you :)

**Comment by christianromney** [comment]
Awesome, can't wait to try it out. Thanks!

**Comment by eggsyntax** [comment]
Bah. Crashes on cljs because there's no timeout version of deref there. Fixing.

**Comment by eggsyntax** [comment]
Fixed in 0.1.12.
